# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\NIS3366-ClipboardDetector\ClipboardDetector\ui\resource\ui\dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dashboard(object):
    def setupUi(self, dashboard):
        dashboard.setObjectName("dashboard")
        dashboard.resize(749, 571)
        self.frame = CardWidget(dashboard)
        self.frame.setGeometry(QtCore.QRect(20, 110, 711, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.listWidget = FlipView(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(50, 20, 600, 431))
        self.listWidget.setObjectName("listWidget")
        self.frame_2 = CardWidget(dashboard)
        self.frame_2.setGeometry(QtCore.QRect(20, 40, 711, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = StrongBodyLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 671, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(dashboard)
        QtCore.QMetaObject.connectSlotsByName(dashboard)

    def retranslateUi(self, dashboard):
        _translate = QtCore.QCoreApplication.translate
        dashboard.setWindowTitle(_translate("dashboard", "Form"))
        self.label.setText(_translate("dashboard", "实时风险仪表盘：显示当日敏感操作占比"))
from qfluentwidgets import CardWidget, FlipView, StrongBodyLabel
